# This is your sidebar TOC. The sidebar code loops through sections here and provides the appropriate formatting.

entries:
- title: Sidebar
  product: Product1
  version: 1.0
  folders:

  - title: Getting Started
    folderitems:
    - title: Product 1 home
      url: /p1_landing_page.html
    - title: Sample 1
      url: /p1_sample1.html
    - title: Sample 2
      url: /p1_sample2.html
    - title: Sample 3
      url: /p1_sample3.html

  - title: Another heading
    folderitems:
    - title: Sample 4
      url: /p1_sample4.html
    - title: Sample 5
      url: /p1_sample5.html
    - title: Sample 6
      url: /p1_sample6.html
    - title: Sample 7
      url: /p1_sample7.html
